name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Download previous best model if it exists
    - name: Download previous best model
      uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: best-model
        path: models/
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Train model
      env:
        PYTORCH_ENABLE_MPS_FALLBACK: 1
      run: |
        python train.py
    
    - name: Run tests
      env:
        PYTORCH_ENABLE_MPS_FALLBACK: 1
      run: |
        pytest -v -s test_model.py
    
    # Archive best model
    - name: Archive best model
      uses: actions/upload-artifact@v4
      with:
        name: best-model
        path: models/mnist_model_best.pth
        retention-days: 90