name: ML Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision
        pip install pytest numpy opencv-python albumentations
        pip install matplotlib tqdm
    
    - name: Run tests
      run: |
        pytest test_model.py -v
    
    - name: Train model
      run: |
        python train.py

    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/
        retention-days: 90