name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision tqdm pytest
        # If you add more dependencies, create and use requirements.txt
    
    - name: Train model
      run: |
        python train.py
    
    - name: Run tests
      run: |
        pytest -v -s test_model.py
    
    - name: Archive model artifacts
      uses: actions/upload-artifact@v2
      with:
        name: trained-model
        path: models/ 